; PlatformIO Project Configuration File for TravelBuddy ESP32 Node
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
